/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.toolsteam.Demo;

import org.joda.time.LocalTime;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        LocalTime time = new LocalTime();
	System.out.println("Local time is : " +time);
	System.out.println(new App().getGreeting());
    }
}
